server:
  address: ':65535'

auth:
  headerkey: 'X-45xnec8cfgsdoy568iadbavirn0g7zue'
  headervalue: '6b8a312s1uj7jzqht7ou70m886kqy68ki9b39nbdz88i2y2rqc9ucqhncuw3bnirw27t5enaatsr8hau'

loki:
  endpoint: ''
  username: ''
  password: ''