server:
  address: ':65535'

auth:
  headerkey: 'X-45xnec8cfgsdoy568iadbavirn0g7zue'
  headervalue: 'm$&Bcd%X59WB5@iRWB#r02!flR8j47PsjfkZnjVrS*&o@DQpVbJAf3NDI#z5THzNvtr*UO7m!Au$4GUXVAM04wpdb&mwOV^uhtkysYp4^NtF!6VV6mBc$RUsUmZhZi#u'

loki:
  endpoint: ''
  username: ''
  password: ''