name: frontend data refresh
on:
  # schedule:
  #   - cron: "30 4 * * *"
  workflow_dispatch:
jobs:
  frontend-data-refresh:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: unpack
        run: |
          SSHSTATS_NODENAMES=$(jq -r '.[]' fe/assets/nodenames.json | tr '\n' ' ')
          echo "SSHSTATS_NODENAMES=$SSHSTATS_NODENAMES" >> "$GITHUB_ENV"
      - name: download
        run: |
          for nodename in $SSHSTATS_NODENAMES; do
            echo "Downloading $nodename.json"
            curl -v                                                                   \
              -H "{{ env.SSHSTATS_API_AUTH_KEY }}: {{ env.SSHSTATS_API_AUTH_VALUE }}" \
              --output-dir fe/data/logins                                             \
              -o "$value.json"                                                        \
              "https://monkfish-app-ss3gb.ondigitalocean.app/stats/$value"
          done
      - name: store
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: |
            fe/data/logins/*.json
