name: playbooks
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "in/**"
jobs:
  ansible:
    name: Run Ansible
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Emit Ansible secrets
        run: |
          echo "${{ secrets.SSHSTATS_ANSIBLE_VAULT_KEY }}" >> ${{github.workspace}}/ansible-vault-pwd
          echo "${{ secrets.SSHSTATS_ANSIBLE_SSH_KEY }}" >> ${{github.workspace}}/ansible-ssh-key
      - name: Lint
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: ${{ github.workspace }}/ansible-vault-pwd
        uses: ansible/ansible-lint@v24.7.0
        with:
          args: in/all.yml
      - name: Run Playbook
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: ${{ github.workspace }}/ansible-vault-pwd
          ANSIBLE_PRIVATE_KEY_FILE: ${{ github.workspace}}/ansible-ssh-key
          ANSIBLE_SSH_EXTRA_ARGS: '-o "StrictHostKeyChecking no"'
        run: |
          ansible-playbook in/all.yml -i in/inventory/honeypots.yml
      - name: Delete Ansible secrets
        if: always()
        run: |
          rm -f ${{github.workspace}}/ansible-vault-pwd
          rm -f ${{github.workspace}}/ansible-ssh-key
